services:
  rent-scraper:
    image: knotatypo/rent-scraper
    container_name: rent-scraper
    ports:
      - "4321:4321"
    environment:
      GEOCODE_API_KEY:
      DB_USER:
      DB_PASS:
      DB_HOST:
      TZ: Australia/Brisbane
    shm_size: 1gb